### ISSUE TITLE
Exercise parser: Move the explanation into the description

### ISSUE THREAD

**Issue by rafaparadela** [47deg/scala-exercises#105]
Some exercises have and convenient explanation after the code, that are taken from a 'scalaDoc` within the code. I think that we should move the explanation to the same scaladoc of description, something like that:

From:

```scala
  /** <code>var</code> parameters in class definition define getter and setter:
    */
  def classWithVarParameter(res0: String, res1: String): ExerciseResult[Unit] = ExerciseRunner("Class With Var Parameter") {

    class ClassWithVarParameter(var description: String)

    val aClass = new ClassWithVarParameter("Flying character")
    aClass.description should be(res0)

    aClass.description = "Flying white character"
    aClass.description should be(res1)

    /** You can define class with private fields:
      *
      * {{{
      * class ClassWithPrivateFields(name: String)
      * val aClass = new ClassWithPrivateFields(\"name\")
      * }}}
      *
      * NOTE: <code>aClass.name</code> is not accessible
      */
  }(∞)
```

To:

```scala
  /** <code>var</code> parameters in class definition define getter and setter:
    *
    * ###Something to set where the description ends and where the explanation starts.###
    *
    * You can define class with private fields:
    *
    * {{{
    * class ClassWithPrivateFields(name: String)
    * val aClass = new ClassWithPrivateFields(\"name\")
    * }}}
    *
    * NOTE: <code>aClass.name</code> is not accessible
    */
  def classWithVarParameter(res0: String, res1: String): ExerciseResult[Unit] = ExerciseRunner("Class With Var Parameter") {

    class ClassWithVarParameter(var description: String)

    val aClass = new ClassWithVarParameter("Flying character")
    aClass.description should be(res0)

    aClass.description = "Flying white character"
    aClass.description should be(res1)
  }(∞)
```

**Comment by andyscott** [comment]
How about an exercise tag that is inserted in the doc comments?

    /** <code>var</code> parameters in class definition define getter and setter:
      *
      * {exercise}
      *
      * You can define class with private fields:
      *
      * {{{
      * class ClassWithPrivateFields(name: String)
      * val aClass = new ClassWithPrivateFields(\"name\")
      * }}}
      *
      * NOTE: <code>aClass.name</code> is not accessible
      */
    def classWithVarParameter(res0: String, res1: String) {

      class ClassWithVarParameter(var description: String)

      val aClass = new ClassWithVarParameter("Flying character")
      aClass.description should be(res0)

      aClass.description = "Flying white character"
      aClass.description should be(res1)
    }

**Comment by rafaparadela** [comment]
This way sounds good

**Comment by andyscott** [comment]
#287
