### ISSUE TITLE
Show code blocks with proper indentation

### ISSUE THREAD

**Issue by dialelo** [47deg/scala-exercises#110]
Exercises are showing up without proper indentation. Indentation of all exercises even those provided by third parties should be automatically formatted with something like scalariform to provide users with a consistent experience.

**Comment by rafaparadela** [comment]
Example of how block are shown right now

![http://cdn.rafp.es/1wp.png](http://cdn.rafp.es/1wp.png)

**Comment by andyscott** [comment]
I have done some work to address this in the exercise parser/compiler. When it extracts an exercise, it cleans up and preserves indentation.

**Comment by raulraja** [comment]
@andyscott Can you share the link to the commit where that is done?

**Comment by andyscott** [comment]
Yes, but unfortunately the repository for the parser is not (yet) public.

**Comment by dialelo** [comment]
Oops, sorry for the overlap @andyscott. I used Scalariform's API for formatting code blocks, here's the commit for reference https://github.com/47deg/scala-exercises/commit/96605cde7aecad825ccc869a50e222fcb90a1ee8

**Comment by raulraja** [comment]
@dialelo @andyscott Moving this to `Ready` since it seems some work was already done in both fronts. Please coordinate among you two to determine if formatting will be performed at parsing time.

**Comment by andyscott** [comment]
I included a minimal solution for this in the fixes I wrote in #184.
