### ISSUE TITLE
Add GitHub user authentication

### ISSUE THREAD

**Issue by rafaparadela** [47deg/scala-exercises#113]
The current Github integration and login came from an example which is far from clean. We need to integrate the login ops as its own algebra in the context Free as we have done with other Biz logic ops.

**Comment by dialelo** [comment]
Note that currently GH authentication can throw runtime exceptions which we should avoid. We have to use Play applicative builders for validating data.

**Comment by rafaparadela** [comment]
When addressing this issue we can considerate to review the permissions we are requesting (we only need github loing and email).

**Comment by andyscott** [comment]
Is this done now? @rafaparadela @raulraja

**Comment by raulraja** [comment]
@andyscott It's half way implemented. We have the algebra, ops and doobie stuff all wired but `com.fortysevendeg.exercises.utils.OAuth2` still needs cleanup

**Comment by dialelo** [comment]
I'm going to clean that up so we can close this, assigning the issue to me.
