### ISSUE TITLE
Add "Progress" persistence layer

### ISSUE THREAD

**Issue by rafaparadela** [47deg/scala-exercises#114]
We should be able to:

- Save/Update the progress: userId, library, section, method, args, state (succeeded/failed) and date 
- Given an userId, library, section, retrieve all the methods and their args (also the state could be useful).
- Given an userId and a library, retrieve the percentage of exercises completed.

**Comment by juanpedromoreno** [comment]
Based on the @rafaparadela 's comments:

The progress should be saved once an exercise is evaluated:

- From the client side, we call to evaluate an exercise (defined by a library, a section and an exercise with the arguments/responses).
- The server evaluates the exercise and then...
- It saves in the progress table a new record with these data: userId, library, section, exercises, args, status (succeded/failed), datetime.
- The server returns the status of the exercise (200 if OK or the error if failed).

Other considerations:

- Each exercise evalution will override the previous record if this exits.
- We're going to persist just the result of the evaluation given an exercise and an user.

Besides that, we’ll need two services/endpoints to retrieve the progress, given an user:

1) Get the Progress data:
* Request: library + section
* Response: exersises + args + status

2) Get the Progess Percentage List
* Request: library
* Response: "the progress"

**Comment by rafaparadela** [comment]
@juanpedromoreno I would like to mention that the second point `2) Get the Progess Percentage List` doesn't require an endpoint. We don't need expose this service. Besides that, LGTM.
