### ISSUE TITLE
Map iteration is misleading

### ISSUE THREAD

**Issue by davidallsopp** [47deg/scala-exercises#14]
The exercise "Map values can be iterated" (http://scala-exercises.47deg.com/koans#maps) is a little misleading, because it relies on the example values coincidentally coming out in the same order that they were put in. 

In general, this is not true for Maps since they are unordered.

**Comment by rafaparadela** [comment]
You are completely right. So I'm going to clarify it,  adding a comment, where such presumption is exposed.

Thank you @davidallsopp
