### ISSUE TITLE
Add main sections for stdlib

### ISSUE THREAD

**Issue by rafaparadela** [47deg/scala-exercises#152]
We should have at last some full sections of stdlib

**Comment by raulraja** [comment]
For the initial MVP we only need 3 sections for the stdlib, cats and shapeless

**Comment by rafaparadela** [comment]
Currently blocked by #182

**Comment by FPerezP** [comment]
@rafaparadela is it still blocked? #182 is merged and closed. Can we merge it?

**Comment by rafaparadela** [comment]
It's not blocked. It has been merged in this branch `rr-SE-167-shapeless-exercises-demo`.

**Comment by rafaparadela** [comment]
By the way, this branch is where, originally, @raulraja and @dialelo are including exercises of Cats and Shapeless.

**Comment by FPerezP** [comment]
Sweet. Thanks for clarifications. Can we close this ticket then?
