### ISSUE TITLE
Add license footer/header

### ISSUE THREAD

**Issue by FPerezP** [47deg/scala-exercises#168]
We need to add a license text to all our files. 

@raulraja, a couple of questions to answer before considering it ready to work on:
* What's the text? Do we have a template? What kind of license are we going to set? 
* Are we going to add it as a footer or as a header?

**Comment by raulraja** [comment]
I'll work on it. The license will be ASL2

**Comment by andyscott** [comment]
I have some code ready to add this automatically to all our files with the sbt header plugin. I've used roughly the same snippet for several projects.
