### ISSUE TITLE
Implicit conversion answer is unexpected

### ISSUE THREAD

**Issue by davidallsopp** [47deg/scala-exercises#17]
http://scala-exercises.47deg.com/koans#implicits

The required answer to: `add(3, 6) should be(__)`  is:   `Int2BigIntegerConvert(9)`

which returns a new BigInteger. Therefore `new BigInteger("9")` would be a valid and more obvious answer.

**Comment by rafaparadela** [comment]
Actually, this exercise has been modified. Has been added more illustrative assertions. 

```
import java.math.BigInteger
implicit def Int2BigIntegerConvert(value: Int): BigInteger = new BigInteger(value.toString)

def add(a: BigInteger, b: BigInteger) = a.add(b)


add(Int2BigIntegerConvert(3), Int2BigIntegerConvert(6)) == Int2BigIntegerConvert(9)  should be()

add(3, 6) == 9  should be()
add(3, 6) == Int2BigIntegerConvert(9)  should be()

add(3, 6) == (9:BigInteger)  should be()
add(3, 6).intValue == 9  should be()
```

Thank you for your contribution.
