### ISSUE TITLE
ScalaDoc markup in comments is not converted to HTML

### ISSUE THREAD

**Issue by dialelo** [47deg/scala-exercises#185]
![scaladoc](https://cloud.githubusercontent.com/assets/409039/13005903/9d5e1e16-d185-11e5-8419-904252eb07f9.png)

Note that headings (using `===`), monospace words (surrounded by backticks), and code blocks (surrounded by `{{{` and `}}}`) are formatted as plain text instead of converting them to HTML.

**Comment by dialelo** [comment]
Also, paragraphs are not respected and everything is rendered as a text blob regardless of the newlines.

**Comment by andyscott** [comment]
I'd like to take a stab at implementing this.

**Comment by andyscott** [comment]
Fixed in #191
