### ISSUE TITLE
Frontpage graphic and Libraries not showing properly

### ISSUE THREAD

**Issue by raulraja** [47deg/scala-exercises#186]
As mentioned in a few meetings before we need to decrease the size of the main photo in the frontpage and leave room for at least 9 library squares which should be primary and visible on page load.

**Comment by raulraja** [comment]
Since this has been reassigned to me? Is there a PR that I need to review?

**Comment by israelperezglez** [comment]
I thought that the ticket should be in QA for you. I forgot put in QA when I send you the PR. Sorry

**Comment by raulraja** [comment]
Do you have a link to the PR?

**Comment by israelperezglez** [comment]
Yes, the link to PR is https://github.com/47deg/scala-exercises/pull/190

**Comment by israelperezglez** [comment]
I will assign the ticket to other people for the QA, Sorry

**Comment by raulraja** [comment]
This was already merged 5 days ago. It can be moved to done.

**Comment by israelperezglez** [comment]
Perfect ;)
