### ISSUE TITLE
Technical Debt - Args should be stored in a better Format

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/scala-exercises#222]
Currently, the exercises args list are stored as a string (varchar(255)).

We should improve the current format (args are stored separated by `##`).

http://www.postgresql.org/docs/9.3/static/arrays.html

**Comment by raulraja** [comment]
Here for doobie details on storing arrays. Let's use `List` though. https://github.com/tpolecat/doobie/blob/master/doc/src/main/tut/13-Extensions-PostgreSQL.md

**Comment by juanpedromoreno** [comment]
@dialelo smart suggestion: Another improvement would be using Meta instances to use the ExerciseType case object, for instance.
