### ISSUE TITLE
Technical Debt - Postgres Enums

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/scala-exercises#256]
We should use Meta instances to use the `ExerciseType` (UserProgress Table) case object with implicit auto-conversions to the varchar and vice versa.

**Comment by dialelo** [comment]
Just to clarify it, do you propose storing our `ExerciseType` ADT as a varchar or using [Postgres enums](http://www.postgresql.org/docs/9.1/static/datatype-enum.html) with a custom type?

**Comment by juanpedromoreno** [comment]
Whichever works best ;)
