### ISSUE TITLE
Index.html shows `stars` value for github `watchers`

### ISSUE THREAD

**Issue by raulraja** [47deg/scala-exercises#31]
![screen shot 2015-04-01 at 11 00 13 am](https://cloud.githubusercontent.com/assets/456796/6937768/55df8aa0-d85e-11e4-994c-72bf14170148.png)
![screen shot 2015-04-01 at 11 00 22 am](https://cloud.githubusercontent.com/assets/456796/6937771/5900cdb6-d85e-11e4-82f4-29f3a0f16444.png)

**Comment by rafaparadela** [comment]
Fixed: http://cl.ly/aTQG
Thank you!
